print('==== DESAFIO 04 ====')
n = input('digite algo: ')
print(('O tipo primitivo desse valor é'), type(n))
print('(1) é numérico? {} '.format(n.isnumeric()))
print('(2) é alfabético? {}'.format(n.isalpha()))
print('(3) é alfanumérico? {}'.format(n.isalnum()))
print('(4) é somente espaço? {}'.format(n.isspace()))
print('(5) tem letras maiúsculas? {} '.format(n.isupper()))
print('(6) tem letras minúsculas? {} '.format(n.islower()))
print('(7) está capitalizada? {} '.format(n.istitle()))
